directories:
  script: scripts
  module: scripts/modules

# Environment variables
env:
  DOCKER_SCOPE: "escapace"

# Enable manage repository scripts
enable:
  - help
  - trust-escapace

# Default script
default: help
